### ISSUE TITLE
Enable softFail or remove "Have a token selected" as a requirement.

### ISSUE THREAD

**Issue by MrVauxs** [Z3nner/lancer-weapon-fx#20] opened 2023-04-27 10:08 UTC
Sequencer provides an option to have animations softFail so they do not throw errors.

This would be a good alternative to a better solution of not requiring the player to have a token selected when rolling attacks. There should be a way of getting the rolling actor from the chat message to then supply to animations. 

Having the game constantly error because you didn't have a token selected, or worse, cause confusion because the animation originated from completely wrong person, can be quite distracting.

**Comment by Z3nner** [comment] 2023-10-12 18:44
We are hoping to have this issue resolved in the next patch by instead providing a fallback logic if no token is selected that should still allow the macro to work as intended.

**Comment by dodgepong** [comment] 2023-11-07 05:18
Resolved by #23

**Closed by dodgepong** 2023-11-07 05:18 UTC
